name: lint_and_style

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.ref == 'refs/heads/master' && github.event_name == 'push')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - run: pip install pylint & pip install -r docker/requirements.txt
    - uses: pre-commit/action@v3.0.1
  pylint:
    runs-on: ubuntu-latest
    needs: pre-commit
    continue-on-error: true
    if: false #github.event_name == 'pull_request' || (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.ref == 'refs/heads/master' && github.event_name == 'push')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - run: pip install pylint & pip install -r docker/requirements.txt
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --hook-stage manual pylint-all --all-files
